<ul class="rd-navbar-nav">
    
    <?php foreach ($this->container as $page): ?>
    
        <?php if (!$page->isVisible() || !$this->navigation()->accept($page)): continue; endif; ?>
        <?php $hasVisiblePages = false; ?>

        <?php if ($page->hasPages()): foreach ($page->getPages() as $child): ?>
            <?php if (!$child->isVisible() || !$this->navigation()->accept($child)): continue; else: ?>
                <?php $hasVisiblePages = true; break; ?>
            <?php endif; ?>
        <?php endforeach; endif; ?>

        <?php if (!$hasVisiblePages): ?>
    
            <li<?=($page->isActive() ? ' class="active"' : '')?>>
                <a href="<?php echo $page->getHref() ?>">
                    <?php echo $this->translate($page->getLabel()) ?>
                </a>
            </li>
            
        <?php else: ?>
            
            <li<?=($page->isActive() ? ' class="active"' : '')?>>
                <a href="#"><?php echo $this->translate($page->getLabel()) ?></a>
                <ul class="rd-navbar-dropdown">
                    <?php foreach ($page->getPages() as $child): ?>
                        <?php if (!$child->isVisible() || !$this->navigation()->accept($child)): continue; else: ?>
                            <li>
                                <a href="<?php echo $child->getHref() ?>">
                                    <?php echo $this->translate($child->getLabel()) ?>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach ?>
                </ul>
            </li>   
            
        <?php endif ?>
            
    <?php endforeach ?>
</ul>