<?php if ($showDelivery || $showBilling): ?>

<!-- address detals -->
<table class="columns" width="100%">
    <tr>
        <td>
            <?php if ($showDelivery): ?>
            <table align="left" class="column">
                <tr>
                    <td>                
                        <h5 class="">Delivery address</h5>
                        <p class="">
                            <?=$addresses->deliveryaddress->getFirstname()?> <?=$addresses->deliveryaddress->getLastname()?><br/>
                            <?=$addresses->deliveryaddress->getAddress1()?> <?=$addresses->deliveryaddress->getAddress2()?><br/>
                            <?=$addresses->deliveryaddress->getCity()?> <?=$addresses->deliveryaddress->getState()?>
                            <?=$addresses->deliveryaddress->getPostcode()?><br/>
                            <?=$addresses->deliveryaddress->getCountryname()?>
                        </p>
                    </td>
                </tr>
            </table>
            <?php endif; ?>

            <?php if ($showBilling): ?>
            <table align="left" class="column">
                <tr>
                    <td>                                            
                        <h5 class="">Billing address</h5>                                
                        <p class="">
                            <?=$addresses->billingaddress->getFirstname()?> <?=$addresses->billingaddress->getLastname()?><br/>
                            <?=$addresses->billingaddress->getAddress1()?> <?=$addresses->billingaddress->getAddress2()?><br/>
                            <?=$addresses->billingaddress->getCity()?> <?=$addresses->billingaddress->getState()?>
                            <?=$addresses->billingaddress->getPostcode()?><br/>
                            <?=$addresses->billingaddress->getCountryname()?>
                        </p>
                    </td>
                </tr>
            </table>
            <?php endif; ?>

            <span class="clear"></span>    

        </td>
    </tr>
</table>
<!-- /address details -->

<?php endif; ?>