<?php include("data/templates/header.phtml"); ?>

<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
            <table>
                <tr>
                    <td>
                        <h4>Hello</h4>
                        <p>
                            Your confirmation code is <strong><?=$code?></strong>. Please note that it expires within <strong><?=$expiry?> minutes</strong>.
                        </p>
                        <p>
                            If you did not trigger this code, then please contact us immediately.
                        </p>
                        <br/>
                    </td>
                </tr>
            </table>
            </div>
                                    
        </td>
        <td></td>
    </tr>
</table>
<!-- /BODY -->

<?php include("data/templates/footer.phtml"); ?>
