<?php include("data/templates/header.phtml"); ?>

<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
            <table>
                <tr>
                    <td>
                        <h4>Hello</h4>
                        <p>
                            This email is to let you know that the following enquiry has been raised.
                        </p>
                            
                        <h4 class="section-header">Enquiry Details</h4>
                        
                        <table class="enquiry-table">
                            <tbody>
                                <tr>
                                    <td style="width: 20%"><strong>Name</strong></td>
                                    <td style="width: 80%"><?=$name?></td>
                                </tr>
                                <tr>
                                    <td><strong>Number</strong></td>
                                    <td><?=$number?></td>
                                </tr>
                                <tr>
                                    <td><strong>Email</strong></td>
                                    <td><?=$email?></td>
                                </tr>
                                <tr>
                                    <td><strong>Date</strong></td>
                                    <td><?=$date?></td>
                                </tr>
                                <tr>
                                    <td><strong>Enquiry</strong></td>
                                    <td><?=$description?></td>
                                </tr>
                            </tbody>
                        </table>
                        
                        <br/>
                    </td>
                </tr>
            </table>
            </div>
                                    
        </td>
        <td></td>
    </tr>
</table>
<!-- /BODY -->

<?php include("data/templates/footer.phtml"); ?>