<!-- FOOTER -->
<table class="footer-wrap" style="border-top: 1px solid #999;">
    <tr>
        <td></td>
        <td class="container">
            
                <!-- content -->
                <div class="content">
                <table>
                <tr>
                    <td align="center">
                        <p>Thank you for shopping at <a href="https://topbeans.co.uk" style="color:#111111;">Top Beans</a>!</p>
                        <a href="https://topbeans.co.uk" title="Top Beans"><img src="<?=$domainPath?>/images/logos/color/full_icons/Icon_144.png" alt=""/></a>
                        <br/><br/>
                        <p><strong><a href="https://topbeans.co.uk" style="color:#111111;">www.topbeans.co.uk</a></strong></p>
                        <p><small>&copy; Top Beans Ltd</small></p>
                    </td>
                </tr>
            </table>
                </div><!-- /content -->
                
        </td>
        <td></td>
    </tr>
</table><!-- /FOOTER -->

</body>
</html>