<?php include("data/templates/header.phtml"); ?>

<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
            <table>
                <tr>
                    <td>
                        <h4>Hello</h4>
                        <p>
                            Thank you for placing your order with Top Beans. This email is to confirm your that order has been placed successfully. 
                            We will send you a dispatch email once your item(s) have dispatched.
                        </p>
                            
                        <h4 class="section-header">Order Details</h4>
                        
                        <table class="order-table">
                            <thead>
                                <tr style="border-bottom: 1px solid #aaa;">
                                    <th style="width: 25%">Type</th>
                                    <th style="width: 25%">Name</th>
                                    <th style="width: 30%">Qty</th>
                                    <th style="width: 20%">Cost</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($orders as $o): ?>
                                <tr>
                                    <td>
                                        <strong>
                                        <?php if ($o->getIspurchase()) : ?>
                                            Purchase
                                        <?php elseif ($o->getIspaidsample()) : ?>
                                            Sample
                                        <?php elseif ($o->getIsfreesample()) : ?>
                                            Sample (Free)
                                        <?php endif; ?>
                                        </strong>
                                    </td>
                                    <td><?=$o->getName()?></td>
                                    <td>
                                        <?php if ($o->getIspurchase()) : ?>
                                            <?=$o->getQuantity()?> &times; <?=$o->getPackagingunit()?>
                                        <?php elseif ($o->getIssample()) : ?>
                                            <?=$o->getQuantity()?> <?=$o->getPricebaseunit()?>
                                        <?php endif; ?>
                                    </td>
                                    <td>
                                        <?php if ($o->getIspurchase() || $o->getIspaidsample()) : ?>
                                            &pound;<?=$o->getItemprice()?>
                                        <?php elseif ($o->getIsfreesample()) : ?>
                                            &pound;0.00
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                <?php endforeach;?>
                            </tbody>
                            
                            <tfoot>
                                <tr>
                                    <td><strong>Shipping (Free)</strong></td>
                                    <td></td>
                                    <td></td>
                                    <td><strong>&pound;0.00</strong></td>
                                </tr>
                                <tr>
                                    <td><strong>Total</strong></td>
                                    <td></td>
                                    <td></td>
                                    <td><strong>&pound;<?=$orderTotal?></strong></td>
                                </tr>
                            </tfoot>
                        </table>

                        <h4 class="section-header">Delivery and Billing Addresses</h4>
                        
                        <!-- address detals -->
                        <table class="columns" width="100%">
                            <tr>
                                <td>
                                    <table align="left" class="column">
                                        <tr>
                                            <td>                
                                                <h5 class="">Delivery address</h5>
                                                <p class="">
                                                    <?=$deliveryAddress->getFirstname()?> <?=$deliveryAddress->getLastname()?><br/>
                                                    <?=$deliveryAddress->getAddress1()?> <?=$deliveryAddress->getAddress2()?><br/>
                                                    <?=$deliveryAddress->getCity()?> <?=$deliveryAddress->getState()?>
                                                    <?=$deliveryAddress->getPostcode()?><br/>
                                                    <?=$deliveryAddress->getCountryname()?>
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                                    
                                    <table align="left" class="column">
                                        <tr>
                                            <td>                                            
                                                <h5 class="">Billing address</h5>                                
                                                <p class="">
                                                    <?=$billingAddress->getFirstname()?> <?=$billingAddress->getLastname()?><br/>
                                                    <?=$billingAddress->getAddress1()?> <?=$billingAddress->getAddress2()?><br/>
                                                    <?=$billingAddress->getCity()?> <?=$billingAddress->getState()?>
                                                    <?=$billingAddress->getPostcode()?><br/>
                                                    <?=$billingAddress->getCountryname()?>
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                                    
                                    <span class="clear"></span>    
                                    
                                </td>
                            </tr>
                        </table>
                        <!-- /address details -->
                        
                        <h4 class="section-header">Cancellations and Returns</h4>
                        <p>
                            In order to cancel PART or ALL of your order, please click on the following link.
                            You will require the Order number (<strong><?=strtoupper($orderGroupKey)?></strong>) to complete the process:
                        </p>
                        
                        <p>
                            <a href="<?=$domainPath?>/Cancellations/index" title="Top Beans"><?=$domainPath?>/Cancellations/index</a>
                        </p>
                        
                        <p>
                            However, once we have dispatched the order, then you will have to return it before it can be cancelled.
                            All returns are at your expense and must be sent to the following address:
                        </p>
                        <p>
                            Top Beans Ltd<br/>
                            36 Erleigh Court Gardens<br/>
                            Reading
                            RG6 1EH<br/>
                            United Kingdom
                        </p>
                        <!--p>
                            Please review our terms and conditions for more information.
                        </p-->
                        <br/>
                        
                        
                    </td>
                </tr>
            </table>
            </div>
                                    
        </td>
        <td></td>
    </tr>
</table>
<!-- /BODY -->

<?php include("data/templates/footer.phtml"); ?>
