<?php include("data/templates/header.phtml"); ?>

<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
            <table>
                <tr>
                    <td>
                        <h4>Hello</h4>
                        <p>
                            Thank you for placing your order with Top Beans. This email is to confirm your that order has been placed successfully. 
                            We will send you a dispatch email once your item(s) have dispatched.
                        </p>
                            
                        <h4 class="section-header">Order Details</h4>
                        <?php $showShipping = true; include("data/templates/items.phtml"); ?>

                        <h4 class="section-header">Delivery and Billing Addresses</h4>
                        <?php $showDelivery = true; $showBilling = true; include("data/templates/addresses.phtml"); ?>
                        
                        <h4 class="section-header">Cancellations and Returns</h4>
                        <p>
                            In order to cancel PART or ALL of your order, please click on the following link.
                            You will require the Order number (<strong><?=strtoupper($orderGroupKey)?></strong>) to complete the process:
                        </p>
                        
                        <p>
                            <a href="<?=$domainPath?>/Cancellations/index" title="Top Beans"><?=$domainPath?>/Cancellations/index</a>
                        </p>
                        
                        <p>
                            However, once we have dispatched the order, then you will have to return it before it can be cancelled.
                            All returns are at your expense and must be sent to the following address:
                        </p>
                        <p>
                            Top Beans Ltd<br/>
                            36 Erleigh Court Gardens<br/>
                            Reading
                            RG6 1EH<br/>
                            United Kingdom
                        </p>
                        <p>
                            Please review our terms and conditions for more information.
                        </p>
                        
                        <br/>
                    </td>
                </tr>
            </table>
            </div>
                                    
        </td>
        <td></td>
    </tr>
</table>
<!-- /BODY -->

<?php include("data/templates/footer.phtml"); ?>
