<?php include("data/templates/header.phtml"); ?>

<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
            <table>
                <tr>
                    <td>
                        <h4>Hello</h4>
                        <p>
                            The following items could not be refunded. Click here to login and review this order: <a href="<?=$domainPath?>/Admin/index">Admin Login</a>
                        </p>
                        
                            
                        <h4 class="section-header">Refund Failed Items</h4>
                        <?php $showShipping = true; include("data/templates/items.phtml"); ?>
                        
                        <br/>
                    </td>
                </tr>
            </table>
            </div>
                                    
        </td>
        <td></td>
    </tr>
</table>
<!-- /BODY -->

<?php include("data/templates/footer.phtml"); ?>
