<?php include("data/templates/header.phtml"); ?>

<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
            <table>
                <tr>
                    <td>
                        <h4>Hello</h4>
                        <p>
                            We thought you would like to know that the following items have been refunded.
                        </p>
                            

                        <h4 class="section-header">Refunded Items</h4>
                        <?php $showShipping = true; include("data/templates/items.phtml"); ?>
                        
                        <br/>
                    </td>
                </tr>
            </table>
            </div>
                                    
        </td>
        <td></td>
    </tr>
</table>
<!-- /BODY -->

<?php include("data/templates/footer.phtml"); ?>
