<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta name="viewport" content="width=device-width" /><!-- IMPORTANT -->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Order Confirmed</title>
    
<style>
    /* ------------------------------------- 
            GLOBAL 
    ------------------------------------- */
    * { 
        margin:0;
        padding:0;
    }
    * { font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; }
    
    img { 
        max-width: 100%; 
    }
    .collapse {
        margin:0;
        padding:0;
    }
    body {
        -webkit-font-smoothing:antialiased; 
        -webkit-text-size-adjust:none; 
        width: 100%!important; 
        height: 100%;
    }
    
    /* ------------------------------------- 
            ELEMENTS 
    ------------------------------------- */
    a { color: #2BA6CB;}
    
    .btn {
        text-decoration:none;
        color:#FFF;
        background-color:#666;
        width:80%;
        padding:15px 10%;
        font-weight:bold;
        text-align:center;
        cursor:pointer;
        display:inline-block;
    }
    
    p.callout {
        padding:15px;
        text-align:center;
        background-color:#ECF8FF;
        margin-bottom: 15px;
    }
    .callout a {
        font-weight:bold;
        color: #2BA6CB;
    }
    
    .column table { width:100%;}
    .column {
        width: 300px;
        float:left;
    }
    .column tr td { padding: 15px; }
    .column-wrap { 
        padding:0!important; 
        margin:0 auto; 
        max-width:600px!important;
    }
    .columns .column {
        width: 280px;
        min-width: 279px;
        float:left;
    }
    table.columns, table.column, .columns .column tr, .columns .column td {
        padding:0;
        margin:0;
        border:0;
        border-collapse:collapse;
    }
    
    table.order-table {
        text-align: left;
        border-collapse: collapse;
        font-size:14px; 
        line-height:1.6;
    }
    
    table.order-table td, table.order-table th {
        padding: 7px 0;
    }
    
    table.order-table th  {
        border-bottom:1px solid #ccc;
    }
    
    table.order-table > tfoot td  {
        border-top:1px solid #ccc;
        border-bottom:1px solid #ccc;
    }
    
    .section-header {
        border-bottom: 2px solid #999;
        margin-top:20px;
    }
    
    /* ------------------------------------- 
            HEADER 
    ------------------------------------- */
    table.head-wrap { width: 100%;}
    
    .header.container table td.logo { padding: 5px; }
    .header.container table td.label { padding: 5px; padding-left:0px;}
    
    
    /* ------------------------------------- 
            BODY 
    ------------------------------------- */
    table.body-wrap { width: 100%;}
    
    
    /* ------------------------------------- 
            FOOTER 
    ------------------------------------- */
    table.footer-wrap { width: 100%;    clear:both!important;
    }
    .footer-wrap .container td.content  p { border-top: 1px solid rgb(215,215,215); padding-top:15px;}
    .footer-wrap .container td.content p {
        font-size:10px;
        font-weight: bold;
        
    }
    
    
    /* ------------------------------------- 
            TYPOGRAPHY 
    ------------------------------------- */
    h1,h2,h3,h4,h5,h6 {
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; line-height: 1.1; margin-bottom:15px; color:#000;
    }
    h1 small, h2 small, h3 small, h4 small, h5 small, h6 small { font-size: 60%; color: #6f6f6f; line-height: 0; text-transform: none; }
    
    h1 { font-weight:200; font-size: 44px;}
    h2 { font-weight:200; font-size: 37px;}
    h3 { font-weight:500; font-size: 27px;}
    h4 { font-weight:500; font-size: 23px;}
    h5 { font-weight:900; font-size: 17px;}
    h6 { font-weight:900; font-size: 14px; text-transform: uppercase; color:#444;}
    
    .collapse { margin:0!important;}
    
    p, ul { 
        margin-bottom: 10px; 
        font-weight: normal; 
        font-size:14px; 
        line-height:1.6;
    }
    p.lead { font-size:17px; }
    p.last { margin-bottom:0px;}
    
    ul li {
        margin-left:5px;
        list-style-position: inside;
    }
    
    hr {
        border: 0;
        height: 0;
        border-top: 1px dotted rgba(0, 0, 0, 0.1);
        border-bottom: 1px dotted rgba(255, 255, 255, 0.3);
    }
    
    /* --------------------------------------------------- 
            RESPONSIVENESS
            Nuke it from orbit. It's the only way to be sure. 
    ------------------------------------------------------ */
    
    /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
    .container {
        display:block!important;
        max-width:600px!important;
        margin:0 auto!important; /* makes it centered */
        clear:both!important;
    }
    
    /* This should also be a block element, so that it will fill 100% of the .container */
    .content {
        padding:15px;
        max-width:600px;
        margin:0 auto;
        display:block; 
    }
    
    /* Let's make sure tables in the content area are 100% wide */
    .content table { width: 100%; }
    
    /* Be sure to place a .clear element after each set of columns, just to be safe */
    .clear { display: block; clear: both; }
    
    
    /* ------------------------------------------- 
            PHONE
            For clients that support media queries.
            Nothing fancy. 
    -------------------------------------------- */
    @media only screen and (max-width: 600px) {
        
        a[class="btn"] { display:block!important; margin-bottom:10px!important; background-image:none!important; margin-right:0!important;}
    
        div[class="column"] { width: auto!important; float:none!important;}
        
        table.social div[class="column"] {
            width:auto!important;
        }
    
    }
</style>

</head>
 
<body bgcolor="#FFFFFF">

<!-- HEADER -->
<table class="head-wrap" style="border-bottom: 1px solid #999;">
    <tr>
        <td></td>
        <td class="header container">
            
                <div class="content">
                    <table>
                        <tr>
                            <td>
                                <a href="https://topbeans.co.uk" title="Top Beans">
                                    <img src="<?=$domainPath?>/images/logos/color/full_icons/Icon_144.png" alt=""/>
                                </a>
                            </td>
                            <td align="right">
                                <h3 class="collapse">Order Confirmation</h3>
                                Order #<?=strtoupper($orderGroupKey)?>
                            </td>
                        </tr>
                    </table>
                </div>
                
        </td>
        <td></td>
    </tr>
</table><!-- /HEADER -->


<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
            <table>
                <tr>
                    <td>
                        <h4>Hello</h4>
                        <p>
                            Thank you for placing your order with Top Beans. This email is to confirm your order has been placed successfully. 
                            We will send you a dispatch email once your item(s) have dispatched.
                        </p>
                            
                        <h4 class="section-header">Order Details</h4>
                        
                        <table class="order-table">
                            <thead>
                                <tr style="border-bottom: 1px solid #aaa;">
                                    <th style="width: 16.7%">Type</th>
                                    <th style="width: 50%">Name &amp; Qty</th>
                                    <th style="width: 16.7%">Cost</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($orders as $o): ?>
                                <tr>
                                    <td>
                                        <strong>
                                        <?php if ($o->getIspurchase()) : ?>
                                            Purchase
                                        <?php elseif ($o->getIspaidsample()) : ?>
                                            Sample
                                        <?php elseif ($o->getIsfreesample()) : ?>
                                            Sample (Free)
                                        <?php endif; ?>
                                        </strong>
                                    </td>
                                    <td>
                                        <?=$o->getName()?><br/>
                                        <?php if ($o->getIspurchase()) : ?>
                                            <?=$o->getQuantity()?> &times; <?=$o->getPackagingunit()?>
                                        <?php elseif ($o->getIssample()) : ?>
                                            <?=$o->getQuantity()?> <?=$o->getPricebaseunit()?>
                                        <?php endif; ?>
                                    </td>
                                    <td>
                                        <?php if ($o->getIspurchase() || $o->getIspaidsample()) : ?>
                                            &pound;<?=$o->getItemprice()?>
                                        <?php elseif ($o->getIsfreesample()) : ?>
                                            &pound;0.00
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                <?php endforeach;?>
                            </tbody>
                            
                            <tfoot>
                                <tr>
                                    <td><strong>Shipping (Free)</strong></td>
                                    <td></td>
                                    <td><strong>&pound;0.00</strong></td>
                                </tr>
                                <tr>
                                    <td><strong>Total</strong></td>
                                    <td></td>
                                    <td><strong>&pound;<?=$orderTotal?></strong></td>
                                </tr>
                            </tfoot>
                        </table>

                        <h4 class="section-header">Delivery and Billing Addresses</h4>
                        
                        <!-- address detals -->
                        <table class="columns" width="100%">
                            <tr>
                                <td>
                                    <table align="left" class="column">
                                        <tr>
                                            <td>                
                                                <h5 class="">Delivery address</h5>
                                                <p class="">
                                                    <?=$deliveryAddress->getFirstname()?> <?=$deliveryAddress->getLastname()?><br/>
                                                    <?=$deliveryAddress->getAddress1()?> <?=$deliveryAddress->getAddress2()?><br/>
                                                    <?=$deliveryAddress->getCity()?> <?=$deliveryAddress->getState()?>
                                                    <?=$deliveryAddress->getPostcode()?><br/>
                                                    <?=$deliveryAddress->getCountryname()?>
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                                    
                                    <table align="left" class="column">
                                        <tr>
                                            <td>                                            
                                                <h5 class="">Billing address</h5>                                
                                                <p class="">
                                                    <?=$billingAddress->getFirstname()?> <?=$billingAddress->getLastname()?><br/>
                                                    <?=$billingAddress->getAddress1()?> <?=$billingAddress->getAddress2()?><br/>
                                                    <?=$billingAddress->getCity()?> <?=$billingAddress->getState()?>
                                                    <?=$billingAddress->getPostcode()?><br/>
                                                    <?=$billingAddress->getCountryname()?>
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                                    
                                    <span class="clear"></span>    
                                    
                                </td>
                            </tr>
                        </table>
                        <!-- /address details -->
                        
                        <h4 class="section-header">Cancelling your order</h4>
                        <p>
                            If you wish to cancel part or all of your order, then please click on this link and follow the instructions: 
                            <strong><a href="<?=$domainPath?>/Index/clientcancellations" title="Top Beans">Cancellations</a></strong>
                        </p>
                        
                        <p>You will need the following code to activate the cancellations: <strong><?=strtoupper($cancellationCode)?></strong></p>

                        <p>
                            Please, however, note that once the order has been dispatched, then it would have to be returned before it can be cancelled.
                            Please review our terms and conditions for more information.
                        </p>
                        <br/>
                        
                        
                    </td>
                </tr>
            </table>
            </div>
                                    
        </td>
        <td></td>
    </tr>
</table>
<!-- /BODY -->

<!-- FOOTER -->
<table class="footer-wrap" style="border-top: 1px solid #999;">
    <tr>
        <td></td>
        <td class="container">
            
                <!-- content -->
                <div class="content">
                <table>
                <tr>
                    <td align="center">
                        <p>Thank you for shopping at <a href="https://topbeans.co.uk" style="color:#111111;">Top Beans</a>!</p>
                        <a href="https://topbeans.co.uk" title="Top Beans"><img src="<?=$domainPath?>/images/logos/color/full_icons/Icon_144.png" alt=""/></a>
                        <br/><br/>
                        <p><strong><a href="https://topbeans.co.uk" style="color:#111111;">www.topbeans.co.uk</a></strong></p>
                        <p><small>&copy; Top Beans Ltd</small></p>
                    </td>
                </tr>
            </table>
                </div><!-- /content -->
                
        </td>
        <td></td>
    </tr>
</table><!-- /FOOTER -->

</body>
</html>