<section style="background-image: url(/images/bg-image-coffee-in-hands.jpg);" class="section-30 section-sm-40 section-md-66 section-lg-bottom-90 bg-gray-dark page-title-wrap">
  <div class="shell">
    <div class="page-title">
      <h2>Buy or Sample</h2>
    </div>
  </div>
</section>

<section>
    <div class="section-50 section-sm-bottom-75 section-lg-bottom-100 bg-whisper text-secondary">
        <div class="shell">
            <div class="range">
                <div class="cell-xs-12">
                    <buy-or-sample></buy-or-sample>
                </div>
            </div>
        </div>
    </div>

</section>




