<section>
    <div data-loop="false" data-autoplay="false" data-simulate-touch="true" class="swiper-container swiper-slider swiper-variant-1 bg-gray-base">
        <div class="swiper-wrapper text-center">
            <div data-slide-bg="/images/home-slider-1-slide-1.jpg" class="swiper-slide">
                <div class="swiper-slide-caption">
                    <div class="shell">
                        <div class="range range-sm-center">
                            <div class="cell-sm-11 cell-md-10 cell-lg-9">
                                <h2 data-caption-animate="fadeInUp" data-caption-delay="0s" class="slider-header"><?=$this->carouselOne->getTitle()?></h2>
                                <p data-caption-animate="fadeInUp" data-caption-delay="100" class="text-bigger slider-text">
                                    <?=$this->carouselOne->getContent()?>
                                </p>
                                <div class="group-xl-responsive offset-top-30 offset-sm-top-45">
                                    <a data-caption-animate="fadeInUp" data-caption-delay="250" href="#" data-custom-scroll-to="section-mission-vision" class="btn btn-xl btn-white-outline-variant-1">
                                        Find out More
                                    </a>
                                    
                                    <a data-caption-animate="fadeInUp" data-caption-delay="250" href="/Index/buyorsample" class="btn btn-xl btn-primary-contrast">
                                        buy or sample
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div data-slide-bg="/images/home-slider-1-slide-2.jpg" class="swiper-slide">
                <div class="swiper-slide-caption">
                    <div class="shell">
                        <div class="range range-sm-center">
                            <div class="cell-sm-11 cell-md-10 cell-lg-9">
                                <h2 data-caption-animate="fadeInUp" data-caption-delay="0s" class="slider-header"><?=$this->carouselTwo->getTitle()?></h2>
                                <p data-caption-animate="fadeInUp" data-caption-delay="100" class="text-bigger slider-text">
                                    <?=$this->carouselTwo->getContent()?>
                                </p>
                                <div class="group-xl-responsive offset-top-30 offset-sm-top-45">
                                    <a data-caption-animate="fadeInUp" data-caption-delay="250" href="#" data-custom-scroll-to="section-different-grades" class="btn btn-xl btn-white-outline-variant-1">
                                        Coffee Grades
                                    </a>
                                    
                                    <a data-caption-animate="fadeInUp" data-caption-delay="250" href="/Index/buyorsample" class="btn btn-xl btn-primary-contrast">
                                        Buy or Sample
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div data-slide-bg="/images/home-slider-1-slide-3.jpg" class="swiper-slide">
                <div class="swiper-slide-caption">
                    <div class="shell">
                        <div class="range range-sm-center">
                            <div class="cell-sm-11 cell-md-10 cell-lg-9">
                                <h2 data-caption-animate="fadeInUp" data-caption-delay="0s" class="slider-header">
                                    <?=$this->carouselThree->getTitle()?>
                                </h2>
                                <p data-caption-animate="fadeInUp" data-caption-delay="100" class="text-bigger slider-text">
                                    <?=$this->carouselThree->getContent()?>
                                </p>
                                <div class="group-xl-responsive offset-top-30 offset-sm-top-45">
                                    <a data-caption-animate="fadeInUp" data-caption-delay="250" href="/Index/approach" class="btn btn-xl btn-white-outline-variant-1">
                                        Our Approach
                                    </a>
                                    
                                    <a data-caption-animate="fadeInUp" data-caption-delay="250" href="/Index/buyorsample" class="btn btn-xl btn-primary-contrast">
                                        Buy or Sample
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="swiper-scrollbar"></div>
        <div class="swiper-nav-wrap">
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
        </div>
    </div>
</section>

<section id="section-mission-vision" class="section-50 section-sm-90 section-lg-top-120 section-lg-bottom-145">
    <div class="shell">
        <div class="range range-md-bottom range-sm-center">
            <div data-wow-duration="2s" data-wow-offset="200" class="cell-sm-10 cell-md-5 wow fadeInLeft">
                <p class="h3 offset-top-0"><?=$this->moreThanCoffee->getTitle()?></p>
                
                <p class="offset-top-40 text-secondary">
                    <?=$this->moreThanCoffee->getContent()?>
                </p>
                
                <a href="/Index/buyorsample" class="btn btn-xl btn-primary">Buy or Sample</a>
            </div>
            <div class="cell-sm-11 cell-md-7 offset-top-40 offset-sm-top-60 offset-md-top-0">
                <div class="image-group">
                    <figure data-wow-duration=".9s" data-wow-delay=".4s" data-wow-offset="80" class="wow fadeInRightMedium">
                        <img src="/images/home-2-340x340.jpg" alt="" />
                    </figure>
                    <figure data-wow-duration=".9s" data-wow-delay=".8s" data-wow-offset="200" class="wow fadeInRightSmall">
                        <img src="/images/home-1-340x340.png" alt="" />
                    </figure>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="section-different-grades" data-on="false" data-md-on="true" style="background-image: url(/images/parallax-1.jpg);" class="rd-parallax bg-gray-base bg-image">
    <div data-speed="0.33" data-type="media" data-url="/images/parallax-1.jpg" class="rd-parallax-layer"></div>
    <div data-speed="0" data-type="html" class="rd-parallax-layer">
        <div class="section-50 section-sm-75 section-lg-top-0 section-lg-bottom-120">
            <div class="shell">
                <div class="range range-sm-center">
                    <div class="cell-sm-11 cell-md-10 cell-lg-9 text-center">
                        <h3><?=$this->gradesOfCoffee->getName()?></h3>
                        <p>
                            <?=$this->gradesOfCoffee->getDescription()?>
                        </p>
                    </div>
                </div>
                <div class="range">
                    <?php if ($this->gradesOfCoffeePosts != null && count($this->gradesOfCoffeePosts) > 0): foreach ($this->gradesOfCoffeePosts as $post): ?>
                        <div class="cell-sm-6 cell-md-4 offset-top-50 offset-sm-top-45">
                            <article class="icon-box-vertical">
                                <h5 class="icon-box-header"><?=$post->getTitle()?></h5>
                                <?=$post->getContent()?>
                            </article>
                        </div>
                    <?php endforeach;endif; ?>
                </div>
                <div class="range offset-top-30 offset-sm-top-45">
                    <div class="cell-xs-12 text-center"><a href="/Index/buyorsample" class="btn btn-xl btn-primary">buy or sample</a></div>
                </div>
            </div>
        </div>
    </div>
</section>

<?=$ourTeam->getContent()?>