<section class="section-30 section-sm-40 section-md-66 section-lg-bottom-90 bg-gray-dark page-title-wrap">
  <div class="shell">
    <div class="page-title">
      <h2>Payment</h2>
    </div>
  </div>
</section>

<section class="section-50 section-sm-bottom-75 section-lg-top-90 section-lg-bottom-100 bg-whisper">
    <script src="https://cdn.worldpay.com/v1/worldpay.js"></script>
    <payment world-pay-client-key="<?=$this->worldPayClientKey?>"></payment>
</section>
