<section style="background-image: url(/images/bg-shop.jpg)" class="section-30 section-sm-40 section-md-66 section-lg-bottom-90 bg-gray-dark page-title-wrap">
  <div class="shell">
    <div class="page-title">
      <h2>Your Cart</h2>
    </div>
  </div>
</section>

<section class="section-15 section-sm-40 section-lg-bottom-120">
    <shopping-cart order-complete="<?=$this->orderComplete?>"></shopping-cart>
</section>
