<section style="background-image: url(/images/bg-login.jpg)" class="section-30 section-sm-40 section-md-66 section-lg-bottom-90 bg-gray-dark page-title-wrap">
  <div class="shell">
    <div class="page-title">
      <h2><?=$this->terms->getTitle()?></h2>
    </div>
  </div>
</section>

<section class="section-lg-bottom-120">
    <div class="shell">
        <div class="range range-lg-justify offset-top-30">
            <div class="cell-sm-12 cell-lg-12 text-secondary">
                <div class="inset-sm-right-15 inset-lg-right-0">
                    <?=$this->terms->getContent()?>
                </div>
            </div>
        </div>
    </div>
</section>
